// Written by Claude AI
export const placeholders: string[] = [
    "Send a message to brighten someone's day!",
    "Type your witty thoughts here...",
    "This is your direct line to fun conversations!",
    "Let your fingers do the talking!",
    "Channel your inner wordsmith...",
    "Unleash your emoji artistry in 3...2...1...",
    "Pepper this chat with your unique voice 🎤",
    "Draft clever quips and bad puns to your heart's content",
    "Share your hot takes on pineapples on pizza 🍕",
    "Vent about your least favorite chores here 🧹",
    "Summon your crew with text flares! 🔥",
    "Tap tap tap your joys and woes",
    "Distill your shower arguments here for later",
    "Enlighten us with your pre-caffeine theories",
    "Plot world domination one text at a time 😈",
    "Set your inner monologue loose!",
    "Spark conversational joy here 💡",
    "Query the universe's mysteries aloud",
    "They say third time's the charm...give it a go!",
    "Unbottle those lightning bolt ideas ⚡",
    "Channel your inner meme lord 👑",
    "Doodle your daydreams here 🖍",
    "Tell us what's on your mind 💭",
    "Describe your snack cravings in vivid detail 🍿",
    "Consult the group hive mind about your first date outfit 👗",
    "Break the ice with a hilarious greeting GIF 👋",
    "Brainstorm solutions to society's problems here ⚖️",
    "Who's got weekend trip recommendations? ✈️",
    "Debate a spicy hot take: The Office or Parks & Rec? 📺",
    "Pin your favorite silly pet videos and memes 🐶",
    "Poll your crew on controversial food opinions 🍛",
    "Summarize last night's wild dream sequence here 💤",
    "Pitch your million dollar business idea 💡",
    "Gush about your current TV show obsession 📺",
    "Rant about the latest celebrity gossip here 🤩",
    "Settle the age-old debates: Nature vs nurture? 🧬",
    "Share your unpopular music opinions ⚡",
    "Airing of Grievances Festivus Edition 🎉",
    "Drop your hottest take: Vue or React? 🤔",
    "Share your latest Vue project and code snippets 💻",
    "Troubleshoot your broken Vite build here 🐛",
    "Debate your favorite Supabase features ⚡️",
    "Recommend your top Vue UI framework 🖌",
    "Compare notes on Pinia vs Vuex state 🗃️",
    "Show off your stylish Tailwind components 💅",
    "Discuss emerging web dev trends and fads ☁️",
    "Help! My routes broken after the Vue Router update 🚧",
    "Share tutorials, guides, and explainers to help the community ♥️",
    "State your unpopular web development opinions here 📢",
    "What Supabase solutions blew your mind this week? 🤯",
    "Rant about your JavaScript fatigue 😫",
    "What are the Vue plugins you can't develop without? 🔌",
    "Describe web development in 2022 GIFs and memes 😂",
    "Debate: Is Vite the future of front-end tooling? ⚔️",
];
const getPlaceholder = () => {
    return placeholders[Math.floor(Math.random() * placeholders.length)];
};
export default getPlaceholder;
